# Generated by Django 2.1.7 on 2019-03-17 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WelderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('length_feet', models.IntegerField()),
                ('height_feet', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('design', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Welderorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('date_of_order', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_completion', models.DateTimeField()),
                ('cover', models.FileField(upload_to='')),
                ('welder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='welderitem',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welderapp.Welderorder'),
        ),
    ]
