# Generated by Django 2.1.7 on 2019-03-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welderapp', '0002_auto_20190317_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welderorder',
            name='date_of_completion',
            field=models.DateField(),
        ),
    ]
