# Generated by Django 2.1.7 on 2019-03-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welderapp', '0004_auto_20190321_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welderorder',
            name='date_of_completion',
            field=models.DateField(),
        ),
    ]
